// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskWebApi;

#nullable disable

namespace TaskWebApi.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TaskWebApi.Models.Task", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("task_id");

                    b.Property<bool>("complete")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("task_status");

                    b.Property<bool>("isEditing")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_editing");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("task_name");

                    b.HasKey("id");

                    b.ToTable("task");

                    b.HasData(
                        new
                        {
                            id = "1",
                            complete = false,
                            isEditing = false,
                            name = "Task 1"
                        },
                        new
                        {
                            id = "2",
                            complete = false,
                            isEditing = false,
                            name = "Task 2"
                        },
                        new
                        {
                            id = "3",
                            complete = false,
                            isEditing = false,
                            name = "Task 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
